// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZ9plBF9wC5T6_wFsG5DbJhwqw1DkvEU',
    appId: '1:91246905090:web:9db4099cbdbd58a324241b',
    messagingSenderId: '91246905090',
    projectId: 'test-86df1',
    authDomain: 'test-86df1.firebaseapp.com',
    storageBucket: 'test-86df1.firebasestorage.app',
    measurementId: 'G-KY2Q7SVF4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4yVwBt3ghdZzCfVsQgQqNvTMK9VVVpy4',
    appId: '1:91246905090:android:6bd5da90515975e324241b',
    messagingSenderId: '91246905090',
    projectId: 'test-86df1',
    storageBucket: 'test-86df1.firebasestorage.app',
  );

}